using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerPush : MonoBehaviour
{
    public float distance = 2f;
    public LayerMask boxMask;

    // Start is called before the first frame update
    void Start() {}

    // Update is called once per frame
    void Update() {
        Physics2D.queriesStartInColliders = false;
        RaycastHit2D hit = Physics2D.Raycast(
            transform.position, 
            Vector2.right * transform.localScale.x, 
            distance, 
            boxMask
        );
    }

    void OnDrawGizmos() {
        Gizmos.color = Color.yellow;
        Gizmos.DrawLine(
            transform.position, 
            (Vector2)transform.position + Vector2.right * transform.localScale.x * distance
        );
    }
}
